# This file was generated by GoReleaser. DO NOT EDIT.
cask "dvac" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "babaa0f65d0a63bda55c41b7512ceae1a8a2391ff55655e1f99cb9cd455444ec"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e02f234e268bda7fdabc4122b655b80310a55f838acc93a33e574330470d78f"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "412eb39d301b8c5434ac42bd561f3ae39f2a151a355370ea1509517e4b2c75a1"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4057bd4cfb8eb79252d006fe9c6c26857a6147e29c8ad7bd194f7747333dfcb"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dvac"
  desc "Terminal cleaner for the Docker disk usage your DDEV projects leave behind"
  homepage "https://github.com/epenthesis/dvac"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dvac"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dvac"]
    end
  end

  # No zap stanza required

end
