# This file was generated by GoReleaser. DO NOT EDIT.
cask "dvac" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d1f6763f7912af6c17d6111179bc75b97ed5ac647f4ac01f9eb4311aa966ed4b"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bce487e0f44b41abb6841205dedd308359805770028380f99cb14b0b9440821a"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79e0013598fd4e9acda1d644314abffd3d0708fd3e9be929195fcf4e972cd287"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00cd18ee720ccebd9b209a19d4e188fff98ba22fa1e9d177f07166bf7fff17f4"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dvac"
  desc "Terminal cleaner for the Docker disk usage your DDEV projects leave behind"
  homepage "https://github.com/epenthesis/dvac"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dvac"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dvac"]
    end
  end

  # No zap stanza required

end
