# This file was generated by GoReleaser. DO NOT EDIT.
cask "dvac" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "15e8ee56bd0c6a96eb2246ac83ee8afc38b7bf118ff6a2ee064e7868621ea355"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8eea9f3b3544a1afca2197e9f29caccf8639ee96c1cf56d4f9d04ff38235c278"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8efa7bea3d452a52a1a8502619196f3734734d46e448894f9f4d3592bdb545d8"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "50bfc4a3c40062f9e9cf96b83aa84eabe546beead44e02fe31f3f3d24960ec1a"
      url "https://github.com/epenthesis/dvac/releases/download/v#{version}/dvac_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dvac"
  desc "Terminal cleaner for the Docker disk usage your DDEV projects leave behind"
  homepage "https://github.com/epenthesis/dvac"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dvac"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dvac"]
    end
  end

  # No zap stanza required

end
